--- 
framework: 
  AdminMode: 1
  ApplicationClass: Qooqle
  ApplicationName: Qooqle
  Database: 
    Database: qooqle
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.2
  DevelMode: 1
  L10N: 
    PoDir: share/po
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []

  Plugins: []

  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates

  QQ:
    my_qq_number: 279005114
    my_qq_nickname: ียาเดบ
    my_qq_realname: ียาเดบ
